---
- name: Install Nginx
  import_tasks: install.yml
  tags: install
  # TODO - check for version
  #when: not hostvars[inventory_hostname].ansible_local.hitotito_nginx.installed

- name: Configure sites
  import_tasks: configure.yml
  tags: configure
